<style>
    :root {
        --background-color: <?php echo ($backgroundColor = $this->themeSetting('background_color')) ? $backgroundColor : "#FFFFFF"; ?>;
        --text-color: <?php echo ($textColor = $this->themeSetting('text_color')) ? $textColor : "#444444"; ?>;
        --link-color: <?php echo ($linkColor = $this->themeSetting('link_color')) ? $linkColor : "#4f6780"; ?>;
        --visited-link-color: <?php echo ($visitedLinkColor = $this->themeSetting('visited_link_color')) ? $visitedLinkColor : "#4f6780"; ?>;
        --active-link-color: <?php echo ($activeLinkColor = $this->themeSetting('active_link_color')) ? $activeLinkColor : "#3763a6"; ?>;
        --button-color: <?php echo ($buttonColor = $this->themeSetting('button_color')) ? $buttonColor : "#000000"; ?>;
        --button-text-color: <?php echo ($buttonTextColor = $this->themeSetting('button_text_color')) ? $buttonTextColor : "#FFFFFF"; ?>;
        --site-title-color: <?php echo ($titleColor = $this->themeSetting('site_title_color')) ? $titleColor : "#000000"; ?>;
    }

        <?php if ($themeHeaderBg = $this->themeSettingAssetUrl('header_bg')): ?>
        <?php $themeHeaderBgPosition = $this->themeSetting('banner_position'); ?>
        header {
            background:transparent url(<?php echo $themeHeaderBg; ?>) no-repeat;
            background-position: left <?php echo ($themeHeaderBgPosition) ? $themeHeaderBgPosition : 'center'; ?>;
        }
        <?php endif; ?> 
</style>