<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=PT+Serif:400,700,400italic,700italic');
$this->headScript()->prependFile($this->assetUrl('js/thanksroy.js'));
$this->headScript()->prependFile($this->assetUrl('js/jquery-accessibleMegaMenu.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        
        <style>
            :root {
                --background-color: <?php echo ($backgroundColor = $this->themeSetting('background_color')) ? $backgroundColor : "#FFFFFF"; ?>;
                --text-color: <?php echo ($textColor = $this->themeSetting('text_color')) ? $textColor : "#444444"; ?>;
                --link-color: <?php echo ($linkColor = $this->themeSetting('link_color')) ? $linkColor : "#4f6780"; ?>;
                --visited-link-color: <?php echo ($visitedLinkColor = $this->themeSetting('visited_link_color')) ? $visitedLinkColor : "#4f6780"; ?>;
                --active-link-color: <?php echo ($activeLinkColor = $this->themeSetting('active_link_color')) ? $activeLinkColor : "#3763a6"; ?>;
                --button-color: <?php echo ($buttonColor = $this->themeSetting('button_color')) ? $buttonColor : "#000000"; ?>;
                --button-text-color: <?php echo ($buttonColor = $this->themeSetting('button_text_color')) ? $buttonTextColor : "#FFFFFF"; ?>;
                --title-color: <?php echo ($titleColor = $this->themeSetting('site_title_color')) ? $titleColor : "#000000"; ?>;
            }
        
              <?php if ($themeHeaderBg = $this->themeSettingAssetUrl('header_bg')): ?>
                <?php $themeHeaderBgPosition = $this->themeSetting('banner_position'); ?>
                header {
                    background:transparent url(<?php echo $themeHeaderBg; ?>) no-repeat;
                    background-position: left <?php echo ($themeHeaderBgPosition) ? $themeHeaderBgPosition : 'center'; ?>;
                }
              <?php endif; ?> 
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <?php ($headerHeight = $this->themeSetting('banner_height')) || ($headerHeight = 'small') ?>
        <header class="<?php echo $headerHeight; ?>">
            <h1>
                <a href="<?php echo $site->url(); ?>" class="site-title">
                <?php if ($this->themeSetting('logo')): ?>
                    <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                <?php else: ?>
                    <?php echo $escape($siteTitle); ?>
                <?php endif; ?>
                </a>
            </h1>
        </header>
        <div id="wrap">
            <nav id="primary-nav">
                <div class="menu-button button">Menu</div>
                <?php echo $site->publicNav()->menu()->setPartial('common/accessible-mega-menu.phtml')->renderPartial(); ?>
                <div id="search">
                    <?php echo $this->partial('common/search-form'); ?>
                </div>
            </nav>
    
            <div id="content" role="main" tabindex="-1">
                <?php echo $this->content; ?>
            </div>

        </div>
        <footer>
            <?php if ($footerContent = $this->themeSetting('footer')): ?>
            <?php echo $footerContent; ?>
            <?php else: ?>
                <?php echo $this->translate('Powered by Omeka S'); ?>
            <?php endif; ?>
        </footer>
    <script type="text/javascript">
    jQuery(document).ready(function () {
        ThanksRoy.mobileMenu();
        ThanksRoy.megaMenu('.no-touchevents #primary-nav');
    });
    </script>
    </body>
</html>
